### ISSUE TITLE
Bug on PUSH

### ISSUE THREAD

**Issue by menduz** [mulesoft/api-sync-tool#131]
```
[ERROR] Fri Jul 29 2016 14:38:14 GMT-0300 (ART): Unexpected error.
For more information check the log file: .api-sync.log located in you home folder
[DEBUG] Fri Jul 29 2016 14:38:14 GMT-0300 (ART): TypeError: Cannot read property 'audit' of undefined
    at /Users/agustinmendez/Code/mozart-xapi/node_modules/api-sync/lib/strategies/updateFileStrategy.js:20:66
    at Object.tapHandler (/Users/agustinmendez/Code/mozart-xapi/node_modules/api-sync/node_modules/bluebird/js/main/finally.js:64:23)
    at Object.tryCatcher (/Users/agustinmendez/Code/mozart-xapi/node_modules/api-sync/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/agustinmendez/Code/mozart-xapi/node_modules/api-sync/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/Users/agustinmendez/Code/mozart-xapi/node_modules/api-sync/node_modules/bluebird/js/main/promise.js:581:18)
    at Async._drainQueue (/Users/agustinmendez/Code/mozart-xapi/node_modules/api-sync/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/Users/agustinmendez/Code/mozart-xapi/node_modules/api-sync/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/Users/agustinmendez/Code/mozart-xapi/node_modules/api-sync/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:566:20)
    at tryOnImmediate (timers.js:546:5)
    at processImmediate [as _immediateCallback] (timers.js:525:5)
```

**Comment by juancoen** [comment]
Fixed in #132

**Comment by menduz** [comment]
THANK YOU
